type Query {
    login(email: String!, password: String!): String!
    verifyToken(token: String!): Boolean
}

type Mutation{
    createUser(data: CreateUserInput): String!

}

input CreateUserInput {
    name: String!
    password: String!
    email: String!
    whatsapp: String!
}